// source: slices.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.protocol.SSPacketSlices', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.protocol.SSPacketSlices = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.protocol.SSPacketSlices, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.protocol.SSPacketSlices.displayName = 'proto.protocol.SSPacketSlices';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.protocol.SSPacketSlices.prototype.toObject = function(opt_includeInstance) {
  return proto.protocol.SSPacketSlices.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.protocol.SSPacketSlices} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protocol.SSPacketSlices.toObject = function(includeInstance, msg) {
  var f, obj = {
    seqno: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    totalsize: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    offset: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    packetdata: msg.getPacketdata_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.protocol.SSPacketSlices}
 */
proto.protocol.SSPacketSlices.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.protocol.SSPacketSlices;
  return proto.protocol.SSPacketSlices.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.protocol.SSPacketSlices} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.protocol.SSPacketSlices}
 */
proto.protocol.SSPacketSlices.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setSeqno(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setTotalsize(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setOffset(value);
      break;
    case 4:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setPacketdata(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.protocol.SSPacketSlices.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.protocol.SSPacketSlices.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.protocol.SSPacketSlices} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.protocol.SSPacketSlices.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {number} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeInt32(
      1,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeBytes(
      4,
      f
    );
  }
};


/**
 * required int32 SeqNo = 1;
 * @return {number}
 */
proto.protocol.SSPacketSlices.prototype.getSeqno = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.protocol.SSPacketSlices} returns this
 */
proto.protocol.SSPacketSlices.prototype.setSeqno = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.protocol.SSPacketSlices} returns this
 */
proto.protocol.SSPacketSlices.prototype.clearSeqno = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.protocol.SSPacketSlices.prototype.hasSeqno = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required int32 TotalSize = 2;
 * @return {number}
 */
proto.protocol.SSPacketSlices.prototype.getTotalsize = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.protocol.SSPacketSlices} returns this
 */
proto.protocol.SSPacketSlices.prototype.setTotalsize = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.protocol.SSPacketSlices} returns this
 */
proto.protocol.SSPacketSlices.prototype.clearTotalsize = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.protocol.SSPacketSlices.prototype.hasTotalsize = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * required int32 Offset = 3;
 * @return {number}
 */
proto.protocol.SSPacketSlices.prototype.getOffset = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.protocol.SSPacketSlices} returns this
 */
proto.protocol.SSPacketSlices.prototype.setOffset = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.protocol.SSPacketSlices} returns this
 */
proto.protocol.SSPacketSlices.prototype.clearOffset = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.protocol.SSPacketSlices.prototype.hasOffset = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * required bytes PacketData = 4;
 * @return {!(string|Uint8Array)}
 */
proto.protocol.SSPacketSlices.prototype.getPacketdata = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/**
 * required bytes PacketData = 4;
 * This is a type-conversion wrapper around `getPacketdata()`
 * @return {string}
 */
proto.protocol.SSPacketSlices.prototype.getPacketdata_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getPacketdata()));
};


/**
 * required bytes PacketData = 4;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getPacketdata()`
 * @return {!Uint8Array}
 */
proto.protocol.SSPacketSlices.prototype.getPacketdata_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getPacketdata()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.protocol.SSPacketSlices} returns this
 */
proto.protocol.SSPacketSlices.prototype.setPacketdata = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.protocol.SSPacketSlices} returns this
 */
proto.protocol.SSPacketSlices.prototype.clearPacketdata = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.protocol.SSPacketSlices.prototype.hasPacketdata = function() {
  return jspb.Message.getField(this, 4) != null;
};


goog.object.extend(exports, proto.protocol);
